name: Production build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment variables
        id: vars
        run: |
          echo "::set-output name=CLIENT_VERSION::${GITHUB_SHA::8}"
          echo "::set-output name=CLIENT_DEPLOY_TIME::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - name: Lint frontend application
        run: npm run lint
        working-directory: frontend
      - name: Build frontend application
        run: |
          npm run build
          echo "Client version: ${VITE_CLIENT_VERSION}"
        env:
          VITE_CLIENT_VERSION: ${{ steps.vars.outputs.CLIENT_VERSION }}
          VITE_CLIENT_DEPLOY_TIME: ${{ steps.vars.outputs.CLIENT_DEPLOY_TIME }}
        working-directory: frontend
      - name: Move built app to firebase dir
        run: cp -R frontend/dist firebase/public
      - name: Deploy application to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          entryPoint: "firebase/"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VANLIGFYR }}"
          channelId: live
          projectId: vanligfyr
          target: webapp
      - name: Create release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: frontend
