name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install web app
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          cp -R frontend/build firebase/public
      - name: install firebase and deploy
        run: |
          cd firebase
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VANLIGFYR }}
